# Ansible inventory - Generated by Terraform, do not edit manually
# ==================================================================

# Master node (kubeadm init) — public subnet
[master]
${project}-${env}-master ansible_host=${master_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${key_file} node_type=master

# Worker nodes (private subnet, reachable via bastion = master public IP)
[workers]
%{ for w in worker_hosts ~}
${w.name} ansible_host=${w.private_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${key_file} ansible_ssh_common_args='-o ForwardAgent=yes -o ProxyJump=ubuntu@${w.bastion}' node_type=worker
%{ endfor ~}

# Parent group: all K8s nodes
[k8s_cluster:children]
master
workers

[all:vars]
ansible_python_interpreter=/usr/bin/python3
